# Generated by Django 2.2.5 on 2019-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('teachername', models.CharField(max_length=20)),
                ('teacherevaluation', models.TextField()),
                ('likecount', models.IntegerField()),
                ('isroll_call', models.BooleanField(blank=True)),
                ('isquality', models.BooleanField(blank=True)),
                ('ishighscore', models.BooleanField(blank=True)),
                ('isfunny', models.BooleanField(blank=True)),
                ('isrecommend', models.BooleanField(blank=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='TeacherImformationPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=20)),
                ('teacherclass', models.CharField(max_length=100)),
                ('isprofessor', models.BooleanField(blank=True)),
                ('countisroll_call', models.IntegerField()),
                ('countisquality', models.IntegerField()),
                ('countishighscore', models.IntegerField()),
                ('countisfunny', models.IntegerField()),
                ('countisrecommend', models.IntegerField()),
            ],
        ),
    ]
