# Generated by Django 2.0.7 on 2020-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATES', '0002_auto_20191113_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherImformationPost',
            new_name='TeacherInformationPost',
        ),
        migrations.AlterField(
            model_name='evaluationpost',
            name='timestamp',
            field=models.CharField(max_length=20),
        ),
    ]
